#!/bin/sh
echo "*** starting $(basename $(dirname $(realpath $0))) ***"
exec 2>&1
. /data/etc/virtual-gps/virtual-gps.conf
if [ -n "$VIRTUAL_GPS_NAME" ]; then
  (sleep 15; dbus -y "com.victronenergy.gps.ve_$VIRTUAL_GPS_DEV" /ProductName SetValue "$VIRTUAL_GPS_NAME") &
fi
exec /opt/victronenergy/gps-dbus/gps_dbus -v -s "/dev/$VIRTUAL_GPS_DEV"
