#!/bin/sh

python /opt/victronenergy/dbus_ne-shunt/usb-serial-helper.py False /opt/victronenergy/dbus-ne-shunt/patchfiles/serial-starter.rules

# Declare service in serial starter conf file
SERIAL_STARTER_CONFIG='/etc/venus/serial-starter.conf'
CONFIG='service relay       dbus-ne-shunt'
if ! grep -q "^$CONFIG$" "$SERIAL_STARTER_CONFIG"; then
  echo "$CONFIG" >> "$SERIAL_STARTER_CONFIG"
fi
 