#!/bin/sh

# Remove service from serial starter conf file
SERIAL_STARTER_CONFIG='/etc/venus/serial-starter.conf'
CONFIG='service relay       dbus-ne-shunt'
if grep -q "^$CONFIG$" "$SERIAL_STARTER_CONFIG"; then
  sed -i "/^$CONFIG$/d" "$SERIAL_STARTER_CONFIG"
fi

# Remove configuration files
rm -r /etc/dbus-ne-shunt
