#!/bin/bash

#echo "thisfile:${0}"

SERVICE_NAME=$(basename "${0%.*}") #get file name without path
echo "SERVICE_NAME:${SERVICE_NAME}" #remove the extension from the filename

USB_SERIAL_HELPER_SCRIPT_FILE="${SERVICE_NAME}.usb-serial-helper" 
echo "USB_SERIAL_HELPER_SCRIPT_FILE:${USB_SERIAL_HELPER_SCRIPT_FILE}"

SERIAL_STARTER_RULES_FILE="/etc/udev/rules.d/serial-starter.rules"
DBUS_MESSAGE_PATH="com.victronenergy.packageManager /GuiEditStatus"
DBUS_MESSAGE_PATH=""
VE_SERVICE_MAPPING_NAME="neshunt"

USB_SERIAL_HELPER_ACTION="detect_add" #"detect_add" "add" "remove" 
echo "./${USB_SERIAL_HELPER_SCRIPT_FILE}"

#if false; then
python "${USB_SERIAL_HELPER_SCRIPT_FILE}"\
    "${USB_SERIAL_HELPER_ACTION}"\
    "${SERIAL_STARTER_RULES_FILE}"\
    "${SERVICE_NAME}"\
    "${VE_SERVICE_MAPPING_NAME}"\
    "${DBUS_MESSAGE_PATH}"
#fi

# Declare service in serial starter conf file
SERIAL_STARTER_CONFIG_FILE='/etc/venus/serial-starter.conf'
CONFIG="service ${VE_SERVICE_MAPPING_NAME}"$'\t\t'"${SERVICE_NAME}"
 
#echo -e "config:${CONFIG}"
if ! grep -q "^${CONFIG}$" "${SERIAL_STARTER_CONFIG_FILE}"; then
 echo "adding service mapping config from ${SERIAL_STARTER_CONFIG_FILE}"
 sed -i '1s/^/'"${CONFIG}"'\n/' $SERIAL_STARTER_CONFIG_FILE
fi
 
echo "${dbus-ne-shunt} installed"
