#!/bin/sh
set -e
if [ -z "$D" ]; then
  # Init configuration script if needed
  CONF_FILE="/data/etc/virtual-gps/virtual-gps.conf"
  if [ ! -f "$CONF_FILE" ]; then
    cat << EOF > "$CONF_FILE"
VIRTUAL_GPS_DEV=ttyGPS   # Any tty* name, must be unique
VIRTUAL_GPS_PORT=8500    # Any valid port number
VIRTUAL_GPS_BAUD=4800    # 4800/9600/38400/115200
VIRTUAL_GPS_NAME=""      # Optional name, default is defined by Victron GPS service
EOF
  fi

  # Copy service files for svscan to detect it within seconds and avoid a reboot
  cp -R /opt/victronenergy/service/virtual-gps-udp-redirect/ /service/
  cp -R /opt/victronenergy/service/virtual-gps-start/ /service/
fi
