#!/bin/sh
echo "*** starting $(basename $(dirname $(realpath $0))) ***"
. /data/etc/virtual-gps/virtual-gps.conf
exec /usr/bin/socat -dd "udp4-recv:$VIRTUAL_GPS_PORT" "pty,link=/dev/$VIRTUAL_GPS_DEV,raw,nonblock,echo=0,b$VIRTUAL_GPS_BAUD" 2>&1
