#!/bin/sh

# Declare service in serial starter conf file
SERIAL_STARTER_CONFIG='/etc/venus/serial-starter.conf'
CONFIG='service relay       dbus-relay-board'
if ! grep -q "^$CONFIG$" "$SERIAL_STARTER_CONFIG"; then
  echo "$CONFIG" >> "$SERIAL_STARTER_CONFIG"
fi
